### ISSUE TITLE
AttributeError: 'SubstepTrainer' object has no attribute 'do_grad_scaling'

### ISSUE THREAD

**Issue by msclar** [princeton-nlp/AutoCompressors#13]
Hi,

I am trying to train an AutoCompressor from scratch but I am encountering the following error when executing `bash run/train_llama.sh --fast_attention`:

```
Traceback (most recent call last):
  File "/mmfs1/gscratch/xlab/msclar/Repositories/AutoCompressors/train.py", line 285, in <module>
    main()
  File "/mmfs1/gscratch/xlab/msclar/Repositories/AutoCompressors/train.py", line 240, in main
    train_result = trainer.train(resume_from_checkpoint=last_checkpoint)
  File "/gscratch/xlab/msclar/anaconda3/envs/embed/lib/python3.9/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/gscratch/xlab/msclar/anaconda3/envs/embed/lib/python3.9/site-packages/transformers/trainer.py", line 1860, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/mmfs1/gscratch/xlab/msclar/Repositories/AutoCompressors/substep_trainer.py", line 195, in training_step
    loss, softprompt = self.training_substep(model, input_slice, softprompt, segment_lengths)
  File "/mmfs1/gscratch/xlab/msclar/Repositories/AutoCompressors/substep_trainer.py", line 174, in training_substep
    if self.do_grad_scaling:
AttributeError: 'SubstepTrainer' object has no attribute 'do_grad_scaling'
```

I used to be able to train AutoCompressors a few months ago, so I wonder if the issue is related to any updates either in AutoCompressor or a dependency. Do you happen to know what the issue may be? I am trying to train the model in a single A100.

Also, I believe that to be able to run the current code with the original OPT models one needs to change line 170 of train.py, changing LlamaAutoCompressorModel to AutoCompressorModel.

Thanks in advance!

**Comment by msclar** [comment]
I think this is an issue with transformers==4.35.0. My old experiments on transformers==4.31.0 did not have this issue. I've just tried transformers==4.32.1 and I don't have the same issue. They must have deprecated this param from the base class Trainer.

**Comment by msclar** [comment]
(I'll just keep it open for visibility, feel free to close of course!)

**Comment by CodeCreator** [comment]
Thank you for raising this and providing a solution and sorry if this caused frustration! I have corrected the huggingface version in the README to 4.34.0 which should be the last version compatible with the repo. I will close the issue for now.
